project:
  type: website

website:
  title: "Rachel Rapier"
  description: "Resume of Rachel Rapier."
  navbar:
    title: "Rachel Rapier"
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



